export const Balance = {
  // War Exhaustion
  WAR_EXHAUSTION_ON_DECLARE: 15.0,
  WAR_EXHAUSTION_MONTHLY_ATK: 1.0,
  WAR_EXHAUSTION_MONTHLY_DEF: 0.8,
  WAR_EXHAUSTION_DECAY: 1.5,
  WAR_EXHAUSTION_DECLARE_BLOCK: 60.0,

  // White Peace
  WHITE_PEACE_MIN_MONTHS: 12,
  WHITE_PEACE_STALEMATE_MONTHS: 18,
  WHITE_PEACE_STALEMATE_SCORE: 15,
  WHITE_PEACE_FATIGUE_SCORE: 25,
  WHITE_PEACE_FATIGUE_THRESHOLD: 40.0,
  WHITE_PEACE_MAX_MONTHS: 36,
  WHITE_PEACE_MAX_SCORE: 50,
  WHITE_PEACE_TRUCE_YEARS: 3,
  VICTORY_TRUCE_YEARS: 5,

  // Army
  ARMY_MAINTENANCE_MULT: 1.25,
  SUPPLY_RECOVER_FRIENDLY: 2.5,
  SUPPLY_DRAIN_ENEMY: 0.7,
  SUPPLY_DRAIN_WINTER: 1.2,
  SUPPLY_LOW_THRESHOLD: 25.0,
  SUPPLY_MOVE_SLOW_THRESHOLD: 30.0,
  MORALE_RECOVER_FRIENDLY: 0.3,
  MORALE_DRAIN_LOW_SUPPLY: 0.8,

  // Season Move
  MOVE_CHANCE_WINTER: 0.55,
  MOVE_CHANCE_AUTUMN: 0.85,
  MOVE_CHANCE_LOW_SUPPLY: 0.7,
  MOVE_CHANCE_MIN: 0.2,

  // Season Combat
  SEASON_COMBAT_SPRING: 1.0,
  SEASON_COMBAT_SUMMER: 1.05,
  SEASON_COMBAT_AUTUMN: 0.92,
  SEASON_COMBAT_WINTER: 0.8,

  // Faction
  FACTION_APPEASE_DEFAULT: 25.0,
  FACTION_APPEASE_PLAYER: 30.0,
  FACTION_APPEASE_GOLD: 25.0,
  FACTION_FEAST_APPEASE: 10.0,
  FACTION_DISSOLVE_DISCONTENT: 5.0,
  FACTION_DISSOLVE_POWER: 40.0,

  // Diplomacy
  IMPROVE_RELATIONS_GOLD: 10,
  FEAST_GOLD: 20,
  FEAST_PRESTIGE: 15,
  FEAST_STRESS: -10,
} as const;
